version: "3"
services:
  browserless:
    image: browserless/chrome:release-puppeteer-1.9.0
    environment:
      ENABLE_CORS: "true"
    ports:
    - 3000:3000
    networks:
    - internal
    restart: always

  swagger-editor:
    image: swaggerapi/swagger-editor:v3.6.14
    ports:
    - 80:8080
    networks:
    - internal

networks:
  internal:
